### ISSUE TITLE
Add on does not work with Blender 4.4

### ISSUE THREAD

**Issue by jep9816** [MarshmallowCirno/RadialDuplicator#2]
The add on does not show up in the "N" sidebar for a selected item.

I see this in the Python console:

AttributeError: 'module' object has no attribute 'DATA_PT_gpencil_modifiers'
Exception in module register(): C:\Users\jep98\AppData\Roaming\Blender Foundation\Blender\4.4\scripts\addons\object_radial_duplicator\__init__.py
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.4\4.4\scripts\modules\addon_utils.py", line 515, in enable
    mod.register()
  File "C:\Users\jep98\AppData\Roaming\Blender Foundation\Blender\4.4\scripts\addons\object_radial_duplicator\__init__.py", line 158, in register
    preferences.register()
  File "C:\Users\jep98\AppData\Roaming\Blender Foundation\Blender\4.4\scripts\addons\object_radial_duplicator\modules\preferences\preferences.py", line 172, in register
    register_modal_keymap()
  File "C:\Users\jep98\AppData\Roaming\Blender Foundation\Blender\4.4\scripts\addons\object_radial_duplicator\modules\keymap\modal_keymap.py", line 5, in register_modal_keymap
    modal_keymap = get_preferences().keymaps.get("modal")
                   ^^^^^^^^^^^^^^^^^
  File "C:\Users\jep98\AppData\Roaming\Blender Foundation\Blender\4.4\scripts\addons\object_radial_duplicator\package.py", line 15, in get_preferences

**Comment by MarshmallowCirno** [comment]
The issue should be resolved now.

**Comment by jep9816** [comment]
Thanks I will take a look

Yahoo Mail: Search, Organize, Conquer 
 
  On Tue, Apr 1, 2025 at 1:25, ***@***.***> wrote:    
The issue should be resolved now.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>
MarshmallowCirno left a comment (MarshmallowCirno/RadialDuplicator#2)
The issue should be resolved now.

**Comment by jep9816** [comment]
I reinstalled and it now works, thanks for the quick response!
    On Tuesday, April 1, 2025 at 09:14:10 AM EDT, Jerry Porter ***@***.***> wrote:  
 
 Thanks I will take a look

Yahoo Mail: Search, Organize, Conquer 
 
  On Tue, Apr 1, 2025 at 1:25, ***@***.***> wrote:    
The issue should be resolved now.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>
MarshmallowCirno left a comment (MarshmallowCirno/RadialDuplicator#2)
The issue should be resolved now.
